### ISSUE TITLE
mzXML vs mzML?

### ISSUE THREAD

**Issue by marwa38** [RonanDaly/pimp#1]
Hi team 

I know that is recommended to use mzXML but in my case I am not using bruker so I have mzML and I know that the conversion to mzXML from mzML is not recommended in case I am not using bruker. 

Does mzML formats sounds ok by any means? particularly that it is mentioned here:

<img width="341" alt="image" src="https://github.com/user-attachments/assets/ababa87e-80c9-4c19-8f00-933817a9061f">

Cheers
Marwa

**Comment by RonanDaly** [comment]
mzML files should be fine, I believe we had tested them a long time ago, but never updated the documentation.
