### ISSUE TITLE
Positive mode only?

### ISSUE THREAD

**Issue by marwa38** [RonanDaly/pimp#2]
Hi team 

Should I upload both negative and positive mode? what if I have only positive mode and negative mode is not available?
<img width="722" alt="image" src="https://github.com/user-attachments/assets/f69000ee-0c11-4fac-a9f8-5793d6d77f3c">
Cheers
Marwa

**Comment by RonanDaly** [comment]
The format of the data was hard-coded to the methods used at Glasgow Polyomics, so in this case both positive and negative modes are necessary. In future, we will be much more flexible in what files we can take.

**Comment by marwa38** [comment]
@RonanDaly 
Thanks for your messages. 
I can't even upload my files and I am not sure what is the issue, everytime I upload I found only one uploaded and others doesn't. Any advice? it would be great if an updated video of how to use Pimp could be shared in the userguide to help especially the visual learners. During one of your analysis you are running, it would be great if you can video record and upload a youtube video and share in the userguide.  
<img width="898" alt="image" src="https://github.com/user-attachments/assets/83f5aed4-0b28-4510-bdb3-2052dd5f3b85" />

Clicking on the one blank uploaded gives an error
<img width="613" alt="image" src="https://github.com/user-attachments/assets/f2873931-4a01-4ba1-bddf-ec080d55fd59" />
